### ISSUE TITLE
REACT: Dataset page not loading after changing variable type to derived

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#653] opened 2022-02-22 09:33 UTC
This may be unique to this example, as I have not been able to replicate on the staging, but for dataset https://closer-archivist-us.herokuapp.com/datasets/1020 a variable was type was changed from normal to derived (it did not have any mappings) and now the dataset will not load. I havn't had this problem on the staging Archivist.

**Comment by simonreed** [comment] 2022-03-11 07:46
@HayleyMills the dataset is loading now, is there a specific section i should be looking at or do you think the issue is now fixed by itself?

**Closed** 2022-03-11 09:16 UTC
Labels: bug, High priority, react
