### ISSUE TITLE
When a category is edited Archivist creates a new category instead of updating the original

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#279] opened 2019-01-25 10:59 UTC
This results in orphan categories in the database and in the XML. This may be one of reasons why some XML exports will not load back into Archivist. The new XML exporter for Discovery ingest should prevent these being outputted into the XML, but it will still mean there are orphans in the DB. 

Examples can be seen in closer_CDI were the category was changed from '1. Eat with a spoon or fork.'  to 'Eat with a spoon or fork.' and hm_test_1 were the category was changed from 'Not difficult at all' to 'Not difficult at all test'. In both cases the original category can still be seen in the latest XML, although it is not linked to a code list.

**Comment by HayleyMills** [comment] 2019-02-22 09:04
Note this also applies to instructions.

**Comment by spuddybike** [comment] 2019-07-22 16:20
This is the correct behaviour - any orphaned categories should not be exported

**Comment by spuddybike** [comment] 2019-07-22 16:20
closed as covered by #280

**Comment by HayleyMills** [comment] 2019-08-21 13:56
Tested exporting alspac_02_qht which did not have any orphaned categories or instructions and so I tried to create one in the database by changing a category from 'Agree strongly' to 'Agree strongly. Changed this for test'. This however didn't create a new category but updated the original and so didn't create an orphan. This behavior has changed- Is this correct @spuddybike

I created an orphaned instruction by adding an instruction to qi_A1_a, saving this and then changing it. This created an orphaned instruction which was not referenced in questionitems.

We need the behaviour to be the same across items. In addition, if we are no longer creating new categories when they are changed, then do we need to remove all those previous categories in the DB which are not referenced?

**Comment by spuddybike** [comment] 2019-08-23 09:04
1. are categories unique within a questionnaire.
  a. If this is the case, then we should make a new category, so we dont bork existing code lists (inadvertently)
2. If categories are NOT unique within a questionnaire
 a. if this is the case, then we should update (as this is just a change to the specific relationship between a code and a category.

**Comment by HayleyMills** [comment] 2019-08-23 10:55
The categories are unique within a questionnaire. I checked for duplicate 'Yes' within questionnaires and there were none. 

Tested using alspac_02_qht where Yes was used more then once. Changed code list cs_Yes_No to lower case yes and it did not update the category but it created a new one, leaving the other code list cs_Yes unchanged. I think this behaviour looks okay to me. 

Instructions are also unique within questionnaires, when any change is made it creates a new category whether it is used by more than one question or not. 

If we are happy with the new beahviour of changes to categories then ;
- do need to apply the same rules to instructions 
- do we need to remove orphaned categories/instructions from the DB?

**Comment by HayleyMills** [comment] 2020-01-13 10:07
This is no longer working as expected. Carried out same test as above using alspac_02_qht on the staging server, but instead of the other Yes categories remaining unchanged, they were changed. e.g I edited cs_Yes category 'Yes' to 'Yes999' this also change code list cs_qE8_d. 

It is unclear when this change in behaviour occurred. It was reported on 10/01/2020 on the ONSLS instance, which I have tested, along with the staging server.

**Comment by spuddybike** [comment] 2020-02-04 10:15
@simonreed I think the problem is in https://github.com/CLOSER-Cohorts/archivist/blob/develop/app/controllers/code_lists_controller.rb line 57:58
        if existing_category
          code[:category_id] = existing_category.try(:id)

If it is an existing category AND in >1 codelist then a new category should be created

**Comment by HayleyMills** [comment] 2020-02-06 10:07
Tested on staging and ONLS and it is now working as expected, although you have to refresh the page to see newly added code lists?

**Closed** 2020-05-20 15:50 UTC
Labels: High priority, question
